# #CART_HOST: cart.rajeshit.space
# CART_HOST: cart.backend-{{ env }}.rajeshit.space
# MYSQL_HOST: mysql.rajeshit.space

MYSQL_HOST: mysql-{{ env }}.rajeshit.space
MYSQL_ROOT_USER: root
MYSQL_ROOT_PASSWORD: RoboShop@1
CART_HOST: cart.backend-{{ env }}.rajeshit.space