- name: disable default nginx version
  ansible.builtin.command: dnf module disable nginx -y

- name: enable nginx 1.24 version
  ansible.builtin.command: dnf module enable nginx:1.24 -y

- name: install nginx
  ansible.builtin.dnf:
    name: nginx
    state: present

- name: enable and start the nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes

- name: Remove the html directory #delete the html directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: create html directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

- name: download the frontend content
  ansible.builtin.get_url:
    url: "https://roboshop-artifacts.s3.amazonaws.com/{{ component }}-v3.zip"
    dest: "/tmp/{{ component }}.zip"

- name: unzip the zip file
  ansible.builtin.unarchive:
    src: "/tmp/{{ component }}.zip"
    dest: /usr/share/nginx/html
    remote_src: yes

- name: remove default nginx conf file
  ansible.builtin.file:
    path: /etc/nginx/nginx.conf
    state: absent

- name: copy roboshop nginx conf
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify:
  - Restart nginx


  

  
