# CART_HOST: cart.rajeshit.space
# USER_HOST: user.rajeshit.space
# RABBITMQ_HOST: rabbitmq.rajeshit.space
# PAYMENT_PASSWORD: roboshop123

CART_HOST: cart.backend-{{ env }}.rajeshit.space
USER_HOST: user.backend-{{ env }}.rajeshit.space
RABBITMQ_HOST: rabbitmq-{{ env }}.rajeshit.space
RABBITMQ_USER: roboshop
RABBITMQ_PASSWORD: roboshop123